Specify weaker ciphers because of Java 7 regression
Firefox 20 works fine, but subversion 1.7.8 fails with the below stacktrace:

javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
        at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1492)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:92)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:69)
        at org.owasp.webscarab.model.Message.readLine(Message.java:440)
        at org.owasp.webscarab.model.Request.read(Request.java:98)
        at org.owasp.webscarab.plugin.proxy.ConnectionHandler.run(ConnectionHandler.java:186)
        at java.lang.Thread.run(Thread.java:722)
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1902)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1860)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1843)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1362)
        at sun.security.ssl.SSLSocketImpl.getSession(SSLSocketImpl.java:2189)
        at org.owasp.webscarab.plugin.proxy.ConnectionHandler.negotiateSSL(ConnectionHandler.java:323)
        at org.owasp.webscarab.plugin.proxy.ConnectionHandler.run(ConnectionHandler.java:144)
        ... 1 more
Caused by: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
        at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:323)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:687)
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:63)
        at sun.security.ssl.ServerHandshaker.setupEphemeralECDHKeys(ServerHandshaker.java:1206)
        at sun.security.ssl.ServerHandshaker.trySetCipherSuite(ServerHandshaker.java:1060)
        at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:887)
        at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:620)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:167)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1032)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1328)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        ... 4 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
        at sun.security.pkcs11.wrapper.PKCS11.C_GenerateKeyPair(Native Method)
        at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:314)
        ... 16 more